export const TypeKeys = {
  SET_MOVIE_DETAIL: 'SET_MOVIE_DETAIL',
  SET_MOVIE_DETAIL_LOADING_STATUS: 'SET_MOVIE_DETAIL_LOADING_STATUS',
  SET_MOVIE_CAST_CREW_DURATION: 'SET_MOVIE_CAST_CREW_DURATION',
  RESET_MOVIE_CAST_CREW_DURATION: 'RESET_MOVIE_CAST_CREW_DURATION',
};
