export const TypeKeys = {
  SET_API_KEY: 'SET_API_KEY',
  SET_MOVIES: 'SET_MOVIES',
  GET_MOVIES: 'GET_MOVIES',
  SEARCH_MOVIES: 'SEARCH_MOVIES',
  SET_MOVIES_LOADING_STATUS: 'SET_MOVIES_LOADING_STATUS',
  SET_PAGE_NO: 'SET_PAGE_NO',
  SET_TOTAL_PAGE_NO: 'SET_TOTAL_PAGE_NO',
};
